### PR TITLE
151 - Multiple api/settings requests

### PR DESCRIPTION
**Pull request by jmsm412**
- Updated some packages to their latest versions
- Resolved a browser console error about styled components
- Resolved the multiple API calls issue
- Relocated the serverSettings custom hook

### CODE REVIEW

**Comment by jmsm412** [comment]
Closes #151

**Comment by sarora180673** [comment]
Still seeing multiple api/settings call when switch to Collection view
Screenshot from 2024-08-14 13-06-42

**Comment by SeanM322** [comment]
Знімок екрана 2024-08-29 о 17 57 35
When I visit `/admin/settings` I got this issue
and some styles are broken. For example favorite icon in Single token View page, but I think I can fix it later when you push it to dev

**Comment by jmsm412** [comment]
Partial changelog
Frontend dependencies
- Updated Ethers from v5 to v6
- Updated react-redux from v8 to v9
- Removed redux, redux-sagas, replaced them with @reduxjs/toolkit 
- Moved typescript definitions to dev dependencies
- Minor version updates to react-router-dom and yoti face capture

Frontend refactors
- useDispatch and useSelector are now custom hooks, with this we don't need to declare types when using store data or calling dispatch
- Relocated and refactored the server settings into multiple components
- Tried to enable typescript in most components and resolve any typing issues

Frontend redux store
With latest version we can now use asyncThunks to handle API calls and status flags

- colorStore: renamed to colors, isDarkMode flag now available to check if dark mode is toggled
- contractsStore: split into the web3 redux store for values and useContracts custom hooks for ethers contracts
-- currentChain -> connectedChain
-- realChain -> requestedChain 
- userStore: renamed to user
-- loggedIn -> isLoggedIn
-- removed UserRd and userData fields, all of the information is flat, available in the user store

Backend:
- Added icon color server setting
- User session now stores the login type
- Fixed issue when updating user profile
- Optimized server settings query to database
- new API endpoint: /api/contracts/:contractId/products
- Optimized API endpoint: /api/contracts/full to include offer data and metadata for one token
- Removed API: /api/files/categories because /api/categories did the same functionality
- Optimized API endpoint: /api/media/list to query the total number of results in the same database query

**Comment by sarora180673** [comment]
@jmsm412 Not seeing Connect Wallet  Button
Screenshot from 2024-08-29 21-45-11

**Review by SeanM322 — APPROVED** [review]

**Comment by sarora180673** [comment]
@jmsm412 Getting error on clicking Continue button on Offers page to navigate to next page for Approve  & putting offers on marketplace

Screenshot from 2024-09-03 10-00-38

**Comment by sarora180673** [comment]
@jmsm412 Error while selecting offer during upload of video
Screenshot from 2024-09-03 13-35-21

**Review by sarora180673 — APPROVED** [review]
QA Verified

**Pull request merged**
